// frontend/src/features/public/HomePage.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { getPublicCompanySettings } from './api';
import { CompanySettings } from '../../shared/types';
import { useAuth } from '../../shared/auth';
import { login as loginApi, register as registerApi } from '../auth/api';

export const HomePage = () => {
  const { token, user } = useAuth();
  const navigate = useNavigate();
  const [settings, setSettings] = useState<CompanySettings | null>(null);
  const [tab, setTab] = useState<'login' | 'register'>('login');
  const [loginEmail, setLoginEmail] = useState('');
  const [loginPassword, setLoginPassword] = useState('');
  const [registerName, setRegisterName] = useState('');
  const [registerRole, setRegisterRole] = useState('buyer');
  const [registerEmail, setRegisterEmail] = useState('');
  const [registerPassword, setRegisterPassword] = useState('');
  const [registerPhone, setRegisterPhone] = useState('');
  const [registerAddress, setRegisterAddress] = useState('');
  const [registerCompanyName, setRegisterCompanyName] = useState('');
  const [registerGstNumber, setRegisterGstNumber] = useState('');
  const [error, setError] = useState<string | null>(null);
  const { login } = useAuth();

  useEffect(() => {
    if (token && user) {
      const basePath =
        user.role === 'admin' || user.role === 'super_admin'
          ? '/admin'
          : user.role === 'seller'
            ? '/seller'
            : '/buyer';
      navigate(`${basePath}/dashboard`, { replace: true });
      return;
    }
    getPublicCompanySettings()
      .then(setSettings)
      .catch(() => setSettings(null));
  }, [navigate, token, user]);

  const handleLogin = async (event: React.FormEvent) => {
    event.preventDefault();
    setError(null);
    try {
      const result = await loginApi(loginEmail, loginPassword);
      login(result.token, result.user);
      navigate('/');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Login failed');
    }
  };

  const handleRegister = async (event: React.FormEvent) => {
    event.preventDefault();
    setError(null);
    try {
      await registerApi({
        name: registerName,
        email: registerEmail,
        password: registerPassword,
        role: registerRole,
        phone: registerPhone || undefined,
        address: registerAddress || undefined,
        companyName: registerCompanyName || undefined,
        gstNumber: registerGstNumber || undefined
      });
      setTab('login');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Registration failed');
    }
  };

  return (
    <div className="bg-light">
      <header className="border-bottom bg-white">
        <div className="container py-3 d-flex align-items-center justify-content-between">
          <div className="d-flex align-items-center gap-3">
            {settings?.logoUrl ? (
              <img src={settings.logoUrl} alt="Company logo" style={{ width: 48, height: 48 }} />
            ) : (
              <div className="logo-mark">I</div>
            )}
            <div>
              <strong className="d-block">{settings?.name ?? 'Inventory Control'}</strong>
              <small className="text-muted">{settings?.tagline ?? 'Operate faster with clear stock visibility.'}</small>
            </div>
          </div>
          <div className="d-flex gap-2">
            <button className="btn btn-outline-primary" onClick={() => setTab('login')}>
              Login
            </button>
            <button className="btn btn-primary" onClick={() => setTab('register')}>
              Register
            </button>
          </div>
        </div>
      </header>

      <main className="container py-5">
        <div className="row g-4 align-items-center">
          <div className="col-12 col-lg-6">
            <h1 className="display-6 fw-semibold mb-3">
              {settings?.tagline ?? 'Inventory, purchasing, and sales in one place.'}
            </h1>
            <p className="text-muted">
              {settings?.description ??
                'Centralize inventory, suppliers, and customer orders. Track approvals, fulfillment, and margins with real-time dashboards.'}
            </p>
            <div className="row g-3 mt-4">
              <div className="col-12 col-md-6">
                <div className="card h-100">
                  <div className="card-body">
                    <h6 className="card-title">Inventory Accuracy</h6>
                    <p className="text-muted mb-0">
                      Track stock, locations, and reorder points with clarity.
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-12 col-md-6">
                <div className="card h-100">
                  <div className="card-body">
                    <h6 className="card-title">Order Workflows</h6>
                    <p className="text-muted mb-0">
                      Approvals, receiving, and fulfillment built in.
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-12 col-md-6">
                <div className="card h-100">
                  <div className="card-body">
                    <h6 className="card-title">Analytics</h6>
                    <p className="text-muted mb-0">
                      Dashboards for margins, stock health, and trends.
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-12 col-md-6">
                <div className="card h-100">
                  <div className="card-body">
                    <h6 className="card-title">Role-Based Access</h6>
                    <p className="text-muted mb-0">
                      Admin, seller, and buyer visibility tailored to each user.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="col-12 col-lg-6">
            <div className="card shadow-sm">
              <div className="card-body">
                <div className="btn-group w-100 mb-3" role="group">
                  <button
                    className={`btn ${tab === 'login' ? 'btn-primary' : 'btn-outline-primary'}`}
                    onClick={() => setTab('login')}
                    type="button"
                  >
                    Login
                  </button>
                  <button
                    className={`btn ${tab === 'register' ? 'btn-primary' : 'btn-outline-primary'}`}
                    onClick={() => setTab('register')}
                    type="button"
                  >
                    Register
                  </button>
                </div>

                {error ? <div className="alert alert-danger">{error}</div> : null}

                {tab === 'login' ? (
                  <form onSubmit={handleLogin}>
                    <div className="mb-3">
                      <label className="form-label">Email</label>
                      <input
                        className="form-control"
                        type="email"
                        value={loginEmail}
                        onChange={(e) => setLoginEmail(e.target.value)}
                        required
                      />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Password</label>
                      <input
                        className="form-control"
                        type="password"
                        value={loginPassword}
                        onChange={(e) => setLoginPassword(e.target.value)}
                        required
                      />
                    </div>
                    <button className="btn btn-primary w-100" type="submit">
                      Login
                    </button>
                  </form>
                ) : (
                  <form onSubmit={handleRegister}>
                    <div className="mb-3">
                      <label className="form-label">Full Name</label>
                      <input
                        className="form-control"
                        value={registerName}
                        onChange={(e) => setRegisterName(e.target.value)}
                        required
                      />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Role</label>
                      <select
                        className="form-select"
                        value={registerRole}
                        onChange={(e) => setRegisterRole(e.target.value)}
                      >
                        <option value="buyer">Buyer</option>
                        <option value="seller">Seller</option>
                        <option value="admin">Admin</option>
                        <option value="super_admin">Super Admin</option>
                      </select>
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Company Name</label>
                      <input
                        className="form-control"
                        value={registerCompanyName}
                        onChange={(e) => setRegisterCompanyName(e.target.value)}
                      />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">GST Number</label>
                      <input
                        className="form-control"
                        value={registerGstNumber}
                        onChange={(e) => setRegisterGstNumber(e.target.value)}
                      />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Email</label>
                      <input
                        className="form-control"
                        type="email"
                        value={registerEmail}
                        onChange={(e) => setRegisterEmail(e.target.value)}
                        required
                      />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Password</label>
                      <input
                        className="form-control"
                        type="password"
                        value={registerPassword}
                        onChange={(e) => setRegisterPassword(e.target.value)}
                        required
                      />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Phone</label>
                      <input
                        className="form-control"
                        value={registerPhone}
                        onChange={(e) => setRegisterPhone(e.target.value)}
                      />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Address</label>
                      <input
                        className="form-control"
                        value={registerAddress}
                        onChange={(e) => setRegisterAddress(e.target.value)}
                      />
                    </div>
                    <button className="btn btn-primary w-100" type="submit">
                      Register
                    </button>
                  </form>
                )}
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className="border-top bg-white">
        <div className="container py-4">
          <div className="row g-3">
            <div className="col-12 col-lg-4">
              <strong>{settings?.name ?? 'Inventory Control'}</strong>
              <p className="text-muted small mb-0">
                {settings?.tagline ?? 'Operate faster with clear stock visibility.'}
              </p>
            </div>
            <div className="col-12 col-lg-4">
              <div className="fw-semibold">Contact</div>
              <div className="text-muted small">Phone: +91-90000-00000</div>
              <div className="text-muted small">Email: support@company.com</div>
              <div className="text-muted small">Address: Business Park, City</div>
            </div>
            <div className="col-12 col-lg-4">
              <div className="fw-semibold">Links</div>
              {settings?.websiteUrl ? (
                <a href={settings.websiteUrl} target="_blank" rel="noreferrer">
                  {settings.websiteUrl}
                </a>
              ) : (
                <span className="text-muted small">Company site not set</span>
              )}
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

// frontend-angular/src/app/pages/home-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { catchError, of } from 'rxjs';
import { AuthService } from '../core/auth.service';
import { notify } from '../core/notify';
import { AuthApiService } from '../core/services/auth-api.service';
import { PublicApiService } from '../core/services/public-api.service';
import { CompanySettings } from '../core/types';

@Component({
  selector: 'app-home-page',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
  <div class="bg-light">
    <header class="border-bottom bg-white">
      <div class="container py-3 d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center gap-3">
          <img *ngIf="company?.logoUrl; else noLogo" [src]="company?.logoUrl" alt="Company logo" style="width:48px;height:48px" />
          <ng-template #noLogo><div class="logo-mark">I</div></ng-template>
          <div>
            <strong class="d-block">{{ company?.name || 'Inventory Control' }}</strong>
            <small class="text-muted">{{ company?.tagline || 'Operate faster with clear stock visibility.' }}</small>
          </div>
        </div>
      </div>
    </header>

    <main class="container py-5">
      <div class="row g-4 align-items-center">
        <div class="col-12 col-lg-6">
          <h1 class="display-6 fw-semibold mb-3">{{ company?.tagline || 'Inventory, purchasing, and sales in one place.' }}</h1>
          <p class="text-muted">{{ company?.description || 'Centralize inventory, suppliers, and customer orders.' }}</p>
        </div>
        <div class="col-12 col-lg-6">
          <div class="card shadow-sm">
            <div class="card-body">
              <div class="btn-group w-100 mb-3">
                <button type="button" class="btn" [class.btn-primary]="tab==='login'" [class.btn-outline-primary]="tab!=='login'" (click)="tab='login'">Login</button>
                <button type="button" class="btn" [class.btn-primary]="tab==='register'" [class.btn-outline-primary]="tab!=='register'" (click)="tab='register'">Register</button>
              </div>
              <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

              <form *ngIf="tab==='login'" (ngSubmit)="handleLogin()">
                <div class="mb-3">
                  <label class="form-label">Email</label>
                  <input class="form-control" type="email" [(ngModel)]="loginEmail" name="loginEmail" required />
                </div>
                <div class="mb-3">
                  <label class="form-label">Password</label>
                  <input class="form-control" type="password" [(ngModel)]="loginPassword" name="loginPassword" required />
                </div>
                <button class="btn btn-primary w-100" type="submit">Login</button>
              </form>

              <form *ngIf="tab==='register'" (ngSubmit)="handleRegister()">
                <div class="mb-3">
                  <label class="form-label">Full Name</label>
                  <input class="form-control" [(ngModel)]="registerName" name="registerName" required />
                </div>
                <div class="mb-3">
                  <label class="form-label">Role</label>
                  <select class="form-select" [(ngModel)]="registerRole" name="registerRole">
                    <option value="buyer">Buyer</option>
                    <option value="seller">Seller</option>
                    <option value="admin">Admin</option>
                    <option value="super_admin">Super Admin</option>
                  </select>
                </div>
                <div class="mb-3">
                  <label class="form-label">Company Name</label>
                  <input class="form-control" [(ngModel)]="registerCompanyName" name="registerCompanyName" />
                </div>
                <div class="mb-3">
                  <label class="form-label">GST Number</label>
                  <input class="form-control" [(ngModel)]="registerGstNumber" name="registerGstNumber" />
                </div>
                <div class="mb-3">
                  <label class="form-label">Email</label>
                  <input class="form-control" type="email" [(ngModel)]="registerEmail" name="registerEmail" required />
                </div>
                <div class="mb-3">
                  <label class="form-label">Password</label>
                  <input class="form-control" type="password" [(ngModel)]="registerPassword" name="registerPassword" required />
                </div>
                <div class="mb-3">
                  <label class="form-label">Phone</label>
                  <input class="form-control" [(ngModel)]="registerPhone" name="registerPhone" />
                </div>
                <div class="mb-3">
                  <label class="form-label">Address</label>
                  <input class="form-control" [(ngModel)]="registerAddress" name="registerAddress" />
                </div>
                <button class="btn btn-primary w-100" type="submit">Register</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
  `
})
export class HomePageComponent implements OnInit {
  private auth = inject(AuthService);
  private authApi = inject(AuthApiService);
  private publicApi = inject(PublicApiService);
  private router = inject(Router);

  company: CompanySettings | null = null;
  tab: 'login' | 'register' = 'login';
  error = '';

  loginEmail = '';
  loginPassword = '';
  registerName = '';
  registerRole = 'buyer';
  registerEmail = '';
  registerPassword = '';
  registerPhone = '';
  registerAddress = '';
  registerCompanyName = '';
  registerGstNumber = '';

  ngOnInit() {
    const user = this.auth.user();
    const token = this.auth.token();
    if (token && user) {
      this.redirectByRole(user.role);
      return;
    }
    this.publicApi.getCompany().pipe(catchError(() => of(null))).subscribe((res) => (this.company = res));
  }

  handleLogin() {
    this.error = '';
    this.authApi.login(this.loginEmail, this.loginPassword).subscribe({
      next: (res) => {
        this.auth.login(res.token, res.user);
        notify('success', 'Login successful');
        this.redirectByRole(res.user.role);
      },
      error: (err) => (this.error = err?.error || err?.message || 'Login failed')
    });
  }

  handleRegister() {
    this.error = '';
    this.authApi
      .register({
        name: this.registerName,
        email: this.registerEmail,
        password: this.registerPassword,
        role: this.registerRole,
        phone: this.registerPhone || undefined,
        address: this.registerAddress || undefined,
        companyName: this.registerCompanyName || undefined,
        gstNumber: this.registerGstNumber || undefined
      })
      .subscribe({
        next: () => {
          notify('success', 'Registration submitted');
          this.tab = 'login';
        },
        error: (err) => (this.error = err?.error || err?.message || 'Registration failed')
      });
  }

  private redirectByRole(role: string) {
    const base = role === 'admin' || role === 'super_admin' ? 'admin' : role === 'seller' ? 'seller' : 'buyer';
    this.router.navigateByUrl(`/${base}/dashboard`);
  }
}
