// frontend/src/shared/Pagination.tsx
import { PaginationMeta } from './types';

type Props = {
  meta: PaginationMeta;
  onPageChange: (page: number) => void;
};

export const Pagination = ({ meta, onPageChange }: Props) => {
  const { page, totalPages } = meta;
  const isFirst = page <= 1;
  const isLast = page >= totalPages;

  return (
    <div className="d-flex align-items-center justify-content-between mt-3">
      <span className="text-muted">
        Page {page} of {totalPages}
      </span>
      <div className="btn-group">
        <button
          className="btn btn-outline-primary btn-sm"
          type="button"
          disabled={isFirst}
          onClick={() => onPageChange(page - 1)}
        >
          Prev
        </button>
        <button
          className="btn btn-outline-primary btn-sm"
          type="button"
          disabled={isLast}
          onClick={() => onPageChange(page + 1)}
        >
          Next
        </button>
      </div>
    </div>
  );
};

// frontend-angular/src/app/shared/pagination.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { PaginationMeta } from '../core/types';

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [CommonModule],
  template: `
  <div class="d-flex align-items-center justify-content-between mt-3" *ngIf="meta">
    <span class="text-muted">Page {{ meta.page }} of {{ meta.totalPages }}</span>
    <div class="btn-group">
      <button class="btn btn-outline-primary btn-sm" type="button" [disabled]="meta.page<=1" (click)="pageChange.emit(meta.page-1)">Prev</button>
      <button class="btn btn-outline-primary btn-sm" type="button" [disabled]="meta.page>=meta.totalPages" (click)="pageChange.emit(meta.page+1)">Next</button>
    </div>
  </div>
  `
})
export class PaginationComponent {
  @Input() meta!: PaginationMeta;
  @Output() pageChange = new EventEmitter<number>();
}
